version: '3'
services:
  postgres:
    container_name: final-year-project
    image: postgres:latest
    environment:
      POSTGRES_USER: batch9
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: learningPlatform
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres-data:
    
